# Generated by Django 4.1.2 on 2022-11-23 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='company',
            table='name',
        ),
    ]
