# Generated by Django 4.1.3 on 2022-11-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending_site", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="name",
            new_name="c_name",
        ),
        migrations.RenameField(
            model_name="vacancy",
            old_name="name",
            new_name="v_name",
        ),
        migrations.AlterField(
            model_name="applicants",
            name="file",
            field=models.FileField(
                default="default.docx", upload_to="files/", verbose_name="Файл"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="image",
            field=models.ImageField(
                default="default.jpg", upload_to="images/", verbose_name="Картинка"
            ),
        ),
    ]
