# Generated by Django 4.1.3 on 2022-12-01 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lending_site", "0002_rename_name_company_c_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="company",
            old_name="c_name",
            new_name="name",
        ),
    ]
