# Generated by Django 4.1.2 on 2022-11-23 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lending_site', '0002_alter_company_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Компания', 'verbose_name_plural': 'Компании'},
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='vacancy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lending_site.applicants'),
        ),
        migrations.AlterModelTable(
            name='company',
            table='company',
        ),
    ]
