# Generated by Django 4.1.3 on 2022-12-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending_site", "0003_rename_c_name_company_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vacancy",
            name="v_name",
        ),
        migrations.AddField(
            model_name="vacancy",
            name="name",
            field=models.CharField(
                default="text", max_length=50, verbose_name="Вакансия"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(default="text", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                default="text", max_length=50, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.CharField(
                default="text", max_length=500, verbose_name="Описание"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary",
            field=models.CharField(
                default="000", max_length=64, verbose_name="Заработная плата"
            ),
        ),
    ]
