# Generated by Django 4.1.2 on 2022-11-24 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lending_site', '0003_alter_company_options_alter_vacancy_vacancy_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicants',
            options={'verbose_name': 'Соискатель', 'verbose_name_plural': 'Соискатели'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterModelOptions(
            name='vacancy',
            options={'verbose_name': 'Вакансия', 'verbose_name_plural': 'Вакансии'},
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lending_site.company', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='activated',
            field=models.BooleanField(default=True, verbose_name='Статус активности'),
        ),
        migrations.AlterModelTable(
            name='applicants',
            table='applicants',
        ),
        migrations.AlterModelTable(
            name='contacts',
            table='contacts',
        ),
        migrations.AlterModelTable(
            name='vacancy',
            table='vacancy',
        ),
    ]
