# Generated by Django 4.1.2 on 2022-11-24 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending_site', '0004_alter_applicants_options_alter_contacts_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vacancy',
            old_name='vacancy_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='vacancy',
        ),
    ]
