# Generated by Django 4.1.3 on 2022-12-05 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending_site", "0004_remove_vacancy_v_name_vacancy_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicants",
            name="file",
            field=models.FileField(null=True, upload_to="files/", verbose_name="Файл"),
        ),
        migrations.AlterField(
            model_name="company",
            name="description",
            field=models.TextField(default="О нашей компании", verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                default="Лучшая компания", max_length=50, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="description",
            field=models.TextField(max_length=500, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Вакансия"),
        ),
        migrations.AlterField(
            model_name="vacancy",
            name="salary",
            field=models.CharField(max_length=64, verbose_name="Заработная плата"),
        ),
    ]
