# Generated by Django 4.1.3 on 2022-12-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "lending_site",
            "0005_alter_applicants_file_alter_company_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="activated",
            field=models.BooleanField(default=True, verbose_name="Статус активности"),
        ),
    ]
