# Generated by Django 4.1.3 on 2022-12-07 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending_site", "0008_alter_company_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="contacts",
            name="title",
            field=models.CharField(default=1, max_length=100, verbose_name="Описание"),
            preserve_default=False,
        ),
    ]
