# Generated by Django 4.1.3 on 2022-12-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lending_site", "0009_contacts_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicants",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="files/", verbose_name="Файл"
            ),
        ),
    ]
